### ISSUE TITLE
ltdl.h fix

### ISSUE THREAD

**Issue by kreon** [mikey-austin/greyd#3]
Hi! There is bug in a couple of distros with libltdl: 
in ltdh.h defined lt__PROGRAM__LTX_preloaded_symbols but in libltdl.so it marked as lt_libltdl_LTX_preloaded_symbols.
To fix this add 
#define lt__PROGRAM__LTX_preloaded_symbols lt_libltdl_LTX_preloaded_symbols
to top of src/mod.c

**Comment by mikey-austin** [comment]
Thanks kreon. As this change breaks builds on a system with a correctly functioning libltdl, I added an option so that you can enable your fix when configuring with the **--with-ltdl-fix** flag. This is in the **issue-3** branch now.

Let me know if this does the trick for you and I will merge it in. Also which operating systems were affected? Arch?

**Comment by kreon** [comment]
Not only.
https://www.google.com/search?q=lt__PROGRAM__LTX_preloaded_symbols

**Comment by mikey-austin** [comment]
I see. I'll merge the issue-3 branch and make a 0.7.1 release.

**Comment by kreon** [comment]
Fix:
define should be above include

diff --git a/src/mod.c b/src/mod.c
index 9018ae2..49ee035 100644
--- a/src/mod.c
+++ b/src/mod.c
@@ -23,6 +23,10 @@
 
 #include <config.h>
 
+#ifdef WITH_LTDL_FIX
+# define lt__PROGRAM__LTX_preloaded_symbols lt_libltdl_LTX_preloaded_symbols
+#endif
+
 #ifdef HAVE_LTDL_H
 # include <ltdl.h>
 #else
@@ -31,9 +35,6 @@
 
 #include "mod.h"
 
-#ifdef WITH_LTDL_FIX
-# define lt__PROGRAM__LTX_preloaded_symbols lt_libltdl_LTX_preloaded_symbols
-#endif
 
 extern void
 *Mod_open(Config_section_T section, const char *name)

**Comment by mikey-austin** [comment]
Thanks, fixed in fcec9d5a48028792c808f097dced2960be40d4e6

**Comment by kreon** [comment]
Yep, now it builds fine.
