### ISSUE TITLE
Can't create greyd.db

### ISSUE THREAD

**Issue by helioloureiro** [mikey-austin/greyd#8]
Hi,

If I leave the directory empty, it complains about non-existent file:

could not open /var/greyd/greyd.db: unable to open database file

and  it doesn't create it at all.
If I manually "touch" such file, it fails as well:

db txn start failed: attempt to write a readonly database
sqlite3_step: SQL logic error or missing database
db scan failed

I'm using sqlite3, but the same applies to Berkeley DB.

**Comment by mikey-austin** [comment]
Hi,

It will create the database files automatically. The problem is the permissions of /var/greyd. By default this dir needs to be owned and writable by the greydb user; this is different from the main greyd user.

These settings are configurable in the config:

http://greyd.org/man.php?name=greyd.conf

The user in the general section is the main process's user, and the user in the grey section is for the database management.

They are different users so that a compromised main process can't modify the database.

You can also of course disable the dropping of privileges by setting the drop_privs setting to 0.

Cheers,
Mikey

**Comment by helioloureiro** [comment]
Hi,

Thanks for the prompt response it is fixed.  Indeed ownership was missing.  I assigned to greyd instead greydb.

Closing it.

**Comment by mikey-austin** [comment]
The program could definitely detect this situation, but not sure if it is worth it? Will see how many times this one pops up.
